name: Test PDF Export (Develop)

on:
  push:
    branches: [ develop ]  # Solo se ejecuta en develop
    paths: [ 'README.md' ]
  workflow_dispatch:  # También ejecución manual
    inputs:
      branch:
        description: 'Branch to test'
        required: false
        default: 'develop'

jobs:
  test-pdf-conversion:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: develop  # Asegura que use develop
    
    - name: Debug - Show current setup
      run: |
        echo "Current branch: $(git branch --show-current)"
        echo "README.md exists: $(ls -la README.md)"
        echo "First 5 lines of README:"
        head -5 README.md
    
    - name: Convert images to absolute URLs (for PDF)
      run: |
        # Backup original
        cp README.md README.md.backup
        
        # Convert relative paths to absolute GitHub URLs
        sed -i 's|](assets/|](https://github.com/reignite-dogimax/report/raw/develop/assets/|g' README.md
        sed -i 's|](/assets/|](https://github.com/reignite-dogimax/report/raw/develop/assets/|g' README.md
        
        echo "URLs converted for PDF compatibility"
    
    - name: Test with simple markdown-to-pdf
      uses: baileyjm02/markdown-to-pdf@v1
      with:
        input_path: README.md
        output_dir: test-pdfs/
        build_html: false
    
    - name: Verify PDF was created
      run: |
        ls -la test-pdfs/
        file test-pdfs/README.pdf || echo "PDF not found"
    
    - name: Upload Test PDF
      uses: actions/upload-artifact@v4
      with:
        name: Test-PDF-Develop-${{ github.run_number }}
        path: test-pdfs/README.pdf
        retention-days: 7  # Solo 7 días para pruebas
    
    - name: Restore original README
      run: |
        mv README.md.backup README.md
        echo "Original README restored"